-- Native Price Checker
-- Protocol fee (in native token) per settlement inside an accounting period, read from the
-- monthly batch data aggregate query (4351957, regenerated by cowprotocol/cow-dagster).
-- Consumed by the payout readiness probe in cowprotocol/cow-dagster
-- (cow_dagster/payouts/readiness_probe/assets.py, check_max_network_fee) to flag
-- implausibly large fees caused by bogus native prices before a payout is proposed.
--
-- Parameters:
-- {{start_time}}: the start date of an accounting week
-- {{end_time}}: the end date of an accounting week
-- {{blockchain}}: the corresponding network

with block_range as (
    select
        min("number") as start_block,
        max("number") as end_block
    from {{blockchain}}.blocks
    where time >= cast('{{start_time}}' as timestamp) and time < cast('{{end_time}}' as timestamp)
)

select
    tx_hash,
    protocol_fee / pow(10, 18) as protocol_fee
from "query_4351957(blockchain='{{blockchain}}')"
where block_number >= (select start_block from block_range) and block_number <= (select end_block from block_range)
