-- Query that calculates USD volume generated by Cow Protocol. It's aggregated by time unit set by {{aggregate_by}} and blockchain name
-- Parameters:
--  {{aggregate_by}} - aggregation param, can be Month, Day, Week

SELECT
    DATE_TRUNC('{{aggregate_by}}', block_time) AS aggregate_by,
    blockchain,
    SUM(amount_usd) AS volume
FROM
    cow_protocol.trades
WHERE
    block_date >= DATE(TIMESTAMP '2021-04-01')
    AND token_sold_address NOT IN (SELECT token_address FROM query_3559859) AND token_bought_address NOT IN (SELECT token_address FROM query_3559859)
GROUP BY 1, 2
