name: Sync to Dune
on:
  push:
    branches: [main]

jobs:
  update-queries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed SQL files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            **/*.sql

      - name: Update Queries
        uses: bh2smith/dune-update@f22f6e55197fc8bd7b03e60b270229b58cca6f15 # v0.1.4
        with:
          changedQueries: ${{ steps.changed-files.outputs.changed_files }}
          duneApiKey: ${{ secrets.DUNE_API_KEY }}
