name: Lint
on:
  pull_request:
  push:
    branches: [main]
jobs:
  sqlfluff:
    name: SQLFluff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install SQLFluff
        run: pip install sqlfluff
      - name: Get changed SQL files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.sql
      - name: Run SQLFluff on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          sqlfluff lint ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Skip SQLFluff (no SQL files changed)
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No SQL files changed, skipping SQLFluff"        
  nitpicker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ethanis/nitpicker@v1
        with:
          nitpicks: ".github/nitpicks.yml"
          token: "${{ secrets.GITHUB_TOKEN }}"
